// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRJ3iPhr1ilOmdMuRVCBSOmzF0KvFruEU',
    appId: '1:767270312801:web:65b36153bec81f7fb7c320',
    messagingSenderId: '767270312801',
    projectId: 'fir-chat-72a61',
    authDomain: 'fir-chat-72a61.firebaseapp.com',
    storageBucket: 'fir-chat-72a61.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRR5oua7ZMILbUoXPlxeSbonDWzU0qt7M',
    appId: '1:767270312801:android:b6364db804bff3c8b7c320',
    messagingSenderId: '767270312801',
    projectId: 'fir-chat-72a61',
    storageBucket: 'fir-chat-72a61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExFoFD1pLEVi2AZdwi14VuevFyQnlb9g',
    appId: '1:767270312801:ios:5e49dac8032decfbb7c320',
    messagingSenderId: '767270312801',
    projectId: 'fir-chat-72a61',
    storageBucket: 'fir-chat-72a61.appspot.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExFoFD1pLEVi2AZdwi14VuevFyQnlb9g',
    appId: '1:767270312801:ios:51de59695e1fbc76b7c320',
    messagingSenderId: '767270312801',
    projectId: 'fir-chat-72a61',
    storageBucket: 'fir-chat-72a61.appspot.com',
    iosBundleId: 'com.example.firebaseChat.RunnerTests',
  );
}
